packages:
  - 'client/website'
  - 'backend/api'

catalog:
  astro: ^5.1.5
  "@astrojs/check": ^0.9.4
  "@astrojs/mdx": ^4.0.5
  "@astrojs/netlify": ^6.0.1
  "@astrojs/react": ^4.1.3
  "@astrojs/sitemap": ^3.2.1
  "@astrojs/tailwind": ^5.1.4
  "tailwindcss": ^3.4.17
  "react": "^19.0.0"
  "react-dom": "^19.0.0"
  "@types/react": "^19.0.4"
  "@types/react-dom": "^19.0.2"
  "@radix-ui/react-avatar": "^1.1.1"
  "@radix-ui/react-collapsible": "^1.1.1"
  "@radix-ui/react-dialog": "^1.1.2"
  "@radix-ui/react-dropdown-menu": "^2.1.2"
  "@radix-ui/react-hover-card": "^1.1.2"
  "@radix-ui/react-navigation-menu": "^1.2.1"
  "@radix-ui/react-separator": "^1.1.0"
  "@radix-ui/react-slot": "^1.1.0"
  "@radix-ui/react-tabs": "^1.1.1"
  "@radix-ui/react-tooltip": "^1.1.3"
  "class-variance-authority": "^0.7.0"
  "clsx": "^2.1.1"
  "lucide-react": "^0.453.0"
  "motion": "^11.14.4"
  "tailwind-merge": "^2.5.4"