packages:
  - 'client/website'

catalog:
  astro: ^5.1.5
  "@astrojs/check": ^0.9.4
  "@astrojs/mdx": ^4.0.5
  "@astrojs/netlify": ^6.0.1
  "@astrojs/react": ^4.1.3
  "@astrojs/sitemap": ^3.2.1
  "@astrojs/tailwind": ^5.1.4